---
swagger: "2.0"
info:
  description: "This is a simple bookstore server with a book inventory, users and\
    \ a shopping cart."
  version: "1.0.0"
  title: "BookHub"
  contact:
    email: "luca.maltagliati@mail.polimi.it"
  license:
    name: "Apache-2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/malta895/hypermedia-project/1.0.0"
tags:
- name: "book"
  description: "Available book"
- name: "cart"
  description: "Access to the cart"
- name: "user"
  description: "Operations about user"
- name: "event"
  description: "Operations on event"
- name: "publisher"
  description: "Operations on publisher"
- name: "order"
  description: "Operations about an order"
- name: "review"
  description: "Operations about books reviews"
schemes:
- "https"
- "http"
paths:
  /books:
    get:
      tags:
      - "book"
      summary: "Books filter"
      description: "Filter books by specified criteria"
      operationId: "booksGET"
      produces:
      - "application/json"
      parameters:
      - name: "title"
        in: "query"
        description: "Filter by name\n"
        required: false
        type: "string"
      - name: "not_in_stock"
        in: "query"
        description: "If true returns also books not in stock. Default is false."
        required: false
        type: "boolean"
      - name: "publishers"
        in: "query"
        description: "Filter by publishers' ID\n"
        required: false
        type: "array"
        items:
          type: "integer"
          format: "int64"
        collectionFormat: "multi"
      - name: "authors"
        in: "query"
        description: "Filter by author"
        required: false
        type: "array"
        items:
          type: "integer"
          format: "int64"
        collectionFormat: "multi"
      - name: "ISBN"
        in: "query"
        description: "Filter by ISBN"
        required: false
        type: "integer"
        format: "int64"
      - name: "min_price"
        in: "query"
        description: "Filter by price higher than value"
        required: false
        type: "number"
      - name: "max_price"
        in: "query"
        description: "Filter by price lower than value"
        required: false
        type: "number"
      - name: "genre"
        in: "query"
        description: "Filter by genres"
        required: false
        type: "array"
        items:
          type: "integer"
          format: "int64"
        collectionFormat: "multi"
      - name: "themes"
        in: "query"
        description: "Filter by themes"
        required: false
        type: "array"
        items:
          type: "integer"
          format: "int64"
        collectionFormat: "multi"
      - name: "best_seller"
        in: "query"
        description: "If true returns bestsellers only"
        required: false
        type: "boolean"
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      - name: "limit"
        in: "query"
        description: "Maximum number of items per page. Default is 20 and cannot exceed\
          \ 500."
        required: false
        type: "integer"
      responses:
        200:
          description: "A collection of books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        404:
          description: "No books found"
      x-swagger-router-controller: "Book"
  /books/{bookId}:
    get:
      tags:
      - "book"
      summary: "Find book by ID"
      description: "Returns a book"
      operationId: "getBookById"
      produces:
      - "application/json"
      parameters:
      - name: "bookId"
        in: "path"
        description: "ID of book to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Book"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Book not found"
      x-swagger-router-controller: "Book"
  /books/{bookId}/related:
    get:
      tags:
      - "book"
      summary: "Books similar to a specific book"
      description: "List of books similar to specified book"
      operationId: "relatedBooksGET"
      produces:
      - "application/json"
      parameters:
      - name: "bookId"
        in: "path"
        description: "ID of the book similar to the ones returned"
        required: true
        type: "integer"
        format: "int64"
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      - name: "limit"
        in: "query"
        description: "Maximum number of items per page. Default is 20 and cannot exceed\
          \ 500."
        required: false
        type: "integer"
      responses:
        200:
          description: "A collection of Books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        400:
          description: "Bad Input!"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /user/login:
    post:
      tags:
      - "user"
      summary: "Login"
      description: "Login with a form"
      operationId: "userLoginPOST"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "formData"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful login"
        403:
          description: "Wrong username/password"
      x-swagger-router-controller: "User"
  /user/logout:
    post:
      tags:
      - "user"
      summary: "Logout"
      description: "Login with a form"
      operationId: "userLogoutPOST"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successful logout"
        400:
          description: "Invalid request (were you logged in?)"
      x-swagger-router-controller: "User"
  /user/register:
    post:
      tags:
      - "user"
      summary: "Register"
      description: "Register into the store"
      operationId: "userRegisterPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successful registration"
        403:
          description: "Unauthorized"
      x-swagger-router-controller: "User"
    x-swagger-router-controller: "User"
  /user/delete:
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "Delete an user's account"
      operationId: "userDeletePOST"
      parameters: []
      responses:
        200:
          description: "Successful deletion!"
        400:
          description: "Invalid request"
        403:
          description: "Unauthorized"
        404:
          description: "User not found"
      x-swagger-router-controller: "User"
    x-swagger-router-controller: "User"
  /user/update:
    put:
      tags:
      - "user"
      summary: "Update user's data"
      description: "Put request to modify some of the user's data"
      operationId: "userModifyPUT"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid request"
        403:
          description: "Unathorized"
      x-swagger-router-controller: "User"
  /cart:
    get:
      tags:
      - "cart"
      summary: "View the content of the cart"
      operationId: "cartGET"
      produces:
      - "application/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Cart"
        403:
          description: "Unauthorized"
      x-swagger-router-controller: "Cart"
  /cart/add/{bookId}:
    put:
      tags:
      - "cart"
      summary: "Add/remove elements to the cart"
      operationId: "cartUpdatePUT"
      parameters:
      - name: "bookId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "quantity"
        in: "query"
        description: "Number of copies to add to the cart. Default is 1."
        required: false
        type: "integer"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Bad request"
      x-swagger-router-controller: "Cart"
    x-swagger-router-controller: "Cart"
  /cart/remove/{bookId}:
    delete:
      tags:
      - "cart"
      summary: "Remove items from the cart"
      operationId: "cartRemoveDELETE"
      parameters:
      - name: "bookId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "quantity"
        in: "query"
        description: "Number of copies to remove from the cart"
        required: false
        type: "integer"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Bad request"
      x-swagger-router-controller: "Cart"
    x-swagger-router-controller: "Cart"
  /authors:
    get:
      tags:
      - "author"
      summary: "Get the list of authors"
      operationId: "authorsGET"
      produces:
      - "application/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      - name: "limit"
        in: "query"
        description: "Maximum number of items per page. Default is 20 and cannot exceed\
          \ 500."
        required: false
        type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Author"
        404:
          description: "Author not found!"
      x-swagger-router-controller: "Author"
  /author/{authorId}:
    get:
      tags:
      - "author"
      summary: "Get an author by ID"
      operationId: "authorIdGET"
      produces:
      - "application/json"
      parameters:
      - name: "authorId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Author"
        404:
          description: "Author not found!"
      x-swagger-router-controller: "Author"
  /publishers:
    get:
      tags:
      - "publisher"
      summary: "Get all publishers"
      operationId: "publishersGET"
      produces:
      - "application/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      - name: "limit"
        in: "query"
        description: "Maximum number of items per page. Default is 20 and cannot exceed\
          \ 500."
        required: false
        type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Publisher"
        404:
          description: "Not found!"
      x-swagger-router-controller: "Publisher"
  /publisher/{publisherId}:
    get:
      tags:
      - "publisher"
      summary: "Get a publisher by Id"
      operationId: "publisherIdGET"
      produces:
      - "application/json"
      parameters:
      - name: "publisherId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Publisher"
        404:
          description: "Publisher not found!"
      x-swagger-router-controller: "Publisher"
    x-swagger-router-controller: "Publisher"
  /event/{eventId}:
    get:
      tags:
      - "event"
      summary: "Get an event in wich a book is presented"
      operationId: "eventIdGET"
      produces:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Event"
        404:
          description: "Event not found!"
      x-swagger-router-controller: "Event"
  /events:
    get:
      tags:
      - "event"
      summary: "Get events filtered"
      operationId: "eventGET"
      produces:
      - "application/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      - name: "limit"
        in: "query"
        description: "Maximum number of items per page. Default is 20 and cannot exceed\
          \ 500."
        required: false
        type: "integer"
      responses:
        200:
          description: "Successful operations"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        400:
          description: "Invalid request"
        404:
          description: "No events found!"
      x-swagger-router-controller: "Event"
    x-swagger-router-controller: "Event"
  /order/create:
    post:
      tags:
      - "order"
      summary: "Place a new order"
      description: "Place a new order from the cart"
      operationId: "orderPlacePOST"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successful placement"
        400:
          description: "Bad Request"
        403:
          description: "Unauthorized"
      x-swagger-router-controller: "Order"
    x-swagger-router-controller: "Order"
  /book/{bookId}/reviews:
    get:
      tags:
      - "review"
      - "book"
      summary: "Get reviews of a book"
      description: "Given a book Id, returns all the reviews"
      operationId: "bookReviewsGET"
      produces:
      - "application/json"
      parameters:
      - name: "bookId"
        in: "path"
        description: "Id of the book to get the reviews"
        required: true
        type: "integer"
        format: "int64"
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      - name: "limit"
        in: "query"
        description: "Maximum number of items per page. Default is 20 and cannot exceed\
          \ 500."
        required: false
        type: "integer"
      responses:
        200:
          description: "Successful operations"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Review"
        400:
          description: "Invalid request"
        404:
          description: "No reviews found!"
      x-swagger-router-controller: "Review"
    x-swagger-router-controller: "Review"
  /review/{reviewId}:
    get:
      tags:
      - "review"
      summary: "Get a review by Id"
      operationId: "reviewIdGET"
      produces:
      - "application/json"
      parameters:
      - name: "reviewId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Review"
        404:
          description: "Review not found!"
      x-swagger-router-controller: "Review"
    x-swagger-router-controller: "Review"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      name:
        type: "string"
        example: "Mario"
      surname:
        type: "string"
        example: "Rossi"
      email:
        type: "string"
        format: "email"
      birth_date:
        type: "string"
        format: "date"
      address:
        $ref: "#/definitions/Address"
    title: "User"
    description: "A user of the application."
    example:
      address:
        country: "Italy"
        province: "CO"
        city: "Como"
        address_id: 1
        street_line2: "11"
        street_line1: "Via Valleggio"
        zip_code: "22100"
      surname: "Rossi"
      birth_date: "2000-01-23"
      name: "Mario"
      id: 1
      email: "email"
  Cart:
    type: "object"
    properties:
      user:
        $ref: "#/definitions/User"
      total:
        $ref: "#/definitions/Amount"
      books:
        type: "array"
        items:
          $ref: "#/definitions/Book"
    title: "Cart"
    description: "Order for books"
    example:
      total:
        currency: "EUR"
        value: 11
      books:
      - picture_path: "pic1.jpg"
        price:
          currency: "EUR"
          value: 11
        genre:
        - name: "Horror"
          genre_id: 1
        - name: "Horror"
          genre_id: 1
        theme:
        - name: "name"
          description: "description"
        - name: "name"
          description: "description"
        average_rating: 1.3203313
        id: 1
        title: "Il deserto dei tartari"
        authors:
        - surname: "Rossi"
          name: "Mario"
          biography: "biography"
          picture: "picture"
        - surname: "Rossi"
          name: "Mario"
          biography: "biography"
          picture: "picture"
        status: "Available"
      - picture_path: "pic1.jpg"
        price:
          currency: "EUR"
          value: 11
        genre:
        - name: "Horror"
          genre_id: 1
        - name: "Horror"
          genre_id: 1
        theme:
        - name: "name"
          description: "description"
        - name: "name"
          description: "description"
        average_rating: 1.3203313
        id: 1
        title: "Il deserto dei tartari"
        authors:
        - surname: "Rossi"
          name: "Mario"
          biography: "biography"
          picture: "picture"
        - surname: "Rossi"
          name: "Mario"
          biography: "biography"
          picture: "picture"
        status: "Available"
      user:
        address:
          country: "Italy"
          province: "CO"
          city: "Como"
          address_id: 1
          street_line2: "11"
          street_line1: "Via Valleggio"
          zip_code: "22100"
        surname: "Rossi"
        birth_date: "2000-01-23"
        name: "Mario"
        id: 1
        email: "email"
  Book:
    type: "object"
    required:
    - "price"
    - "title"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      title:
        type: "string"
        example: "Il deserto dei tartari"
      authors:
        type: "array"
        items:
          $ref: "#/definitions/Author"
      price:
        $ref: "#/definitions/Amount"
      picture_path:
        type: "string"
        example: "pic1.jpg"
        description: "Relative path to a picture representing the book\n"
      status:
        type: "string"
        example: "Available"
        description: "Book availability in the inventory"
        enum:
        - "Available"
        - "Out of stock"
      genre:
        type: "array"
        items:
          $ref: "#/definitions/Genre"
      theme:
        type: "array"
        items:
          $ref: "#/definitions/Theme"
      average_rating:
        type: "number"
        format: "float"
        description: "Average rating of the reviews"
        minimum: 1
        maximum: 5
    title: "Book"
    description: "A book for sale in the store"
    example:
      picture_path: "pic1.jpg"
      price:
        currency: "EUR"
        value: 11
      genre:
      - name: "Horror"
        genre_id: 1
      - name: "Horror"
        genre_id: 1
      theme:
      - name: "name"
        description: "description"
      - name: "name"
        description: "description"
      average_rating: 1.3203313
      id: 1
      title: "Il deserto dei tartari"
      authors:
      - surname: "Rossi"
        name: "Mario"
        biography: "biography"
        picture: "picture"
      - surname: "Rossi"
        name: "Mario"
        biography: "biography"
        picture: "picture"
      status: "Available"
  Amount:
    type: "object"
    required:
    - "currency"
    - "value"
    properties:
      value:
        type: "number"
        format: "double"
        minimum: 0.01
        maximum: 1000000000
      currency:
        $ref: "#/definitions/Currency"
    description: "Price\n"
    example:
      currency: "EUR"
      value: 11
  Currency:
    type: "string"
    pattern: "^[A-Z]{3,3}$"
    description: "Currency international code\n"
    example: "EUR"
  Author:
    type: "object"
    required:
    - "name"
    - "surname"
    properties:
      name:
        type: "string"
        example: "Mario"
        description: "First name of the author\n"
      surname:
        type: "string"
        example: "Rossi"
        description: "Surname of the author\n"
      biography:
        type: "string"
        description: "Short biography of the author\n"
      picture:
        type: "string"
        description: "A portrait of the author\n"
    title: "Author"
    description: "An author that has written or co-written some books in the store"
    example:
      surname: "Rossi"
      name: "Mario"
      biography: "biography"
      picture: "picture"
  Address:
    type: "object"
    required:
    - "city"
    - "country"
    - "street_line1"
    - "street_line2"
    - "zip_code"
    properties:
      address_id:
        type: "integer"
        format: "int64"
        example: 1
      street_line1:
        type: "string"
        example: "Via Valleggio"
      street_line2:
        type: "string"
        example: "11"
      city:
        type: "string"
        example: "Como"
      province:
        type: "string"
        example: "CO"
      zip_code:
        type: "string"
        example: "22100"
      country:
        type: "string"
        example: "Italy"
    title: "Address"
    description: "A complete address template, usable in many contexts of the web\
      \ app"
    example:
      country: "Italy"
      province: "CO"
      city: "Como"
      address_id: 1
      street_line2: "11"
      street_line1: "Via Valleggio"
      zip_code: "22100"
  Event:
    type: "object"
    required:
    - "date"
    - "event_id"
    - "location"
    - "name"
    properties:
      event_id:
        type: "integer"
        format: "int64"
        example: 1
        description: "Unique identifier of the event"
      location:
        $ref: "#/definitions/Address"
      name:
        type: "string"
      date:
        type: "string"
        format: "date-time"
    title: "Event"
    description: "An event where some books are presented"
    example:
      date: "2000-01-23T04:56:07.000+00:00"
      event_id: 1
      name: "name"
      location:
        country: "Italy"
        province: "CO"
        city: "Como"
        address_id: 1
        street_line2: "11"
        street_line1: "Via Valleggio"
        zip_code: "22100"
  Publisher:
    type: "object"
    required:
    - "name"
    properties:
      publisher_id:
        type: "integer"
        format: "int64"
        example: 1
      address:
        $ref: "#/definitions/Address"
      name:
        type: "string"
        example: "Zanichelli"
        description: "Name of the editor/publisher"
    title: "Publisher"
    description: "Who edits/publishes a book"
    example:
      publisher_id: 1
      address:
        country: "Italy"
        province: "CO"
        city: "Como"
        address_id: 1
        street_line2: "11"
        street_line1: "Via Valleggio"
        zip_code: "22100"
      name: "Zanichelli"
  Genre:
    type: "object"
    required:
    - "genre_id"
    - "name"
    properties:
      genre_id:
        type: "integer"
        format: "int64"
        example: 1
      name:
        type: "string"
        example: "Horror"
    title: "Genre"
    description: "The genre of the book"
    example:
      name: "Horror"
      genre_id: 1
  Theme:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
      description:
        type: "string"
    title: "Theme"
    description: "The theme of the book"
    example:
      name: "name"
      description: "description"
  Review:
    type: "object"
    required:
    - "book"
    - "rating"
    - "review_id"
    - "user"
    properties:
      review_id:
        type: "integer"
        format: "int64"
      user:
        type: "integer"
        format: "int64"
        description: "User id of who wrote the review"
      title:
        type: "string"
        description: "Title of the review"
      text:
        type: "string"
        description: "Content of the review"
      rating:
        type: "integer"
        format: "int64"
        description: "Rating of the review, expressed in 1 to 5 stars"
        minimum: 1
        maximum: 5
      book:
        type: "integer"
        format: "int64"
        description: "Id of the reviewed book"
    title: "Review"
    description: "A review of a book, with rating and optional title and text"
    example:
      review_id: 0
      book: 5
      rating: 1
      text: "text"
      title: "title"
      user: 6
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
